### ISSUE TITLE
How login and logout views should be

### ISSUE THREAD

**Issue by FarhangAmaji** [wagnerdelima/drf-social-oauth2#136]
How login and logout views should be? is the anything related to tokens (like generating and returning token) or user model like (logout(request) or authenticate(request, username=username, password=password)) should be done in login and logout views?
can you provide some examples?

**Comment by wagnerdelima** [comment]
If by Login you mean creating an auth token, please view the convert-token endpoint. In order to sign the user out, you need to send a request to the revoke-token/ endpoint. This way, a user's token will be removed and its permissions revoked.
You can see both endpoints by running swagger via docker: https://github.com/wagnerdelima/drf-social-oauth2#run-swagger-editor.
