### ISSUE TITLE
Google oauth2 no longer provides access token but the idToken

### ISSUE THREAD

**Issue by MehdiDRISSIB** [wagnerdelima/drf-social-oauth2#159]
Hello @wagnerdelima 

google provide only id_token and no longer accesstoken which is expected in your library

I'm using the api convert-token for google login. Google provide now only the id_token as it's explained here: https://developers.google.com/identity/sign-in/web/backend-auth?hl=en
the api convert-token throws error: "Your credentials aren't allowed" because of this. All my credentials are correct except this one. Please fix the issue.
Many thanks in advance

FYI: @SukiCZ @PrasanthPerumalsamy

**Comment by Hexvortex** [comment]
yeah am also facing same issue

**Comment by Hexvortex** [comment]
@MehdiDRISSIB Have you any solution or work around?

**Comment by MehdiDRISSIB** [comment]
[Here](https://github.com/wagnerdelima/drf-social-oauth2/issues/138#event-8847198525) is a proposed solution but I didn't tested yet. If you do, please give a feedback and the whole code. I'm still waiting for a fix on this library

**Comment by wagnerdelima** [comment]
@MehdiDRISSIB how can I get the id token from google playground (https://developers.google.com/oauthplayground/)? It still gives me the access token. So it's hard to implement the feature. Thanks.

**Comment by SukiCZ** [comment]
@wagnerdelima You can obtain the `token_id` in [Google Identity Service](https://developers.google.com/identity/oauth2/web/guides/migration-to-GIS) which is the recommended way now.

**Comment by wagnerdelima** [comment]
@SukiCZ and @MehdiDRISSIB this answer works. However, there is a little configuring you need to do.

First of all, add the code from the link in this file drf_social_oauth2/backends.py, like so:

![image](https://user-images.githubusercontent.com/7796148/230438254-f962ec93-1d6a-4428-9c1c-4a83590ff68f.png)

The in your settings, replace the green by the blue one. This is the new class you just created.

![image](https://user-images.githubusercontent.com/7796148/230438437-4a231881-230c-4026-ba7c-6ae41731e845.png)

In your request, replace google-oauth2 backend by google-identity.
![image](https://user-images.githubusercontent.com/7796148/230437795-765757b7-3a9c-4403-8081-ff9113f5b5ef.png)

Send the request and success!

I can't make a fix right now because I have to further my studies on this. Soon I will provide a solution with a release tag.

**Comment by MehdiDRISSIB** [comment]
Hello 

I just tried the solution of @wagnerdelima and it works very well. Many thanks !

We are waiting for the solution in the new release

**Comment by wagnerdelima** [comment]
Hi @SukiCZ , @MehdiDRISSIB, @Hexvortex and @vbabiy,

I just publish a new release with the fixes. Thanks for contributing!

**Comment by dreaquil** [comment]
@wagnerdelima Thanks for this fix! I wanted to point out that the docs are out of date on this. Happy to contribute if you'd like.
