### ISSUE TITLE
"name 'IntegrityError' is not defined"

### ISSUE THREAD

**Issue by sarwarmdgolam** [wagnerdelima/drf-social-oauth2#222]
**Describe the bug**
Exception type 'IntegrityError' is not found
 
**To Reproduce**
1. POST http://localhost:8022/auth/convert-token
2. Response shows 500Errors
{
    "detail": [
        "name 'IntegrityError' is not defined"
    ]
}

**Expected behavior**
'IntegrityError' list need to import properly.

**Comment by bojanKuzma** [comment]
I made a PR for this error, it's because some imports of exceptions are missing and the error messages indicates that they are missing, until approval you can just import the missing constant and class with:
`python
from django.db import IntegrityError
from rest_framework.status import HTTP_500_INTERNAL_SERVER_ERROR
`
