### ISSUE TITLE
Invalid token response

### ISSUE THREAD

**Issue by MidoCobra** [wagnerdelima/drf-social-oauth2#47]
while using the token returned from the app in my authorized requests I got this response:

HTTP/1.1 401 Unauthorized
Allow: POST, OPTIONS
Content-Length: 27
Content-Type: application/json
Date: Mon, 22 Mar 2021 02:07:47 GMT
Server: WSGIServer/0.2 CPython/3.6.9
Vary: Accept
WWW-Authenticate: Token
X-Content-Type-Options: nosniff
X-Frame-Options: DENY

{
    "detail": "Invalid token."
}

I tried both access token and refresh token

However the user is registered fine and added to my custom users models and django social model

Thanks in advance

**Comment by MidoCobra** [comment]
I solved the issue it was about my request … now I send the request like this: 
http http://localhost:8000/api/get-wishlist/ "Authorization: Bearer igR4gOhmZd8ISycZ6JJtcNJTs6"

The errored request was:
http http://localhost:8000/api/get-wishlist/ "Authorization: Token igR4gOhmZd8ISycZ6JJtcNJTs6"

but actually this will make some issues in the implemented mobile application, because all API Requests I created in my backend use Token not Bearer, so now the frontend developers will be confused when to send requests using "Bearer" and when to use "Token"...

My Question now, is there is somehow that I should change Bearer To Token in my requests?

**Comment by wagnerdelima** [comment]
Hi @MidoCobra,

You cannot change the bearer token to just token, as far as I know. This comes from python social auth. Otherwise you would  have to study the docs a little deeper. 

Regarding the changes in the non-expired access token, I would not suggest you do that. An access token is a short-lived token. I needs to expire so the client re-authenticates. However, if you would like to change the expiry time of your access tokens you can look at: https://github.com/wagnerdelima/drf-social-oauth2#customize-token-expiration

**Comment by MidoCobra** [comment]
thanks a lot...
appreciating your concern
