### ISSUE TITLE
After getting the convert token, how to get user's username, email ? 

### ISSUE THREAD

**Issue by ibrahimyaacob92** [wagnerdelima/drf-social-oauth2#50]
How to get more data other than access & refresh token after it's being converted by Django ?

**Comment by ibrahimyaacob92** [comment]
im stuck with this and cannot find any resource to proceed.. please help !!
![image](https://user-images.githubusercontent.com/58116068/116013249-b2fe9780-a661-11eb-89c3-3d043031ad94.png)

**Comment by crozarakamilla** [comment]
I am not sure if it's the right approach but you can use the actual token to get the user:

```
usr_id = AccessToken.objects.get(token=request.query_params.get('token')).user_id
user = Usuario.objects.filter(pk=usr_id)
```

**Comment by wagnerdelima** [comment]
In order to get more data like you want, you'd have to overwrite the social python behaviour. This response format is not coming from django itself however social python. I would descourage you from doing that. 

Yes, like @crozarakamilla mentioned you can get the access token like she wrote. Perhaps if you tell us your design we can help you more.

**Comment by ibrahimyaacob92** [comment]
I'm using your workaround @crozarakamilla and it works like charm 👍 
I do think it's convenient feature to get the user profile from the token request, but its too difficult to do I wouldn't mind to close this ticket

**Comment by MohamedMuneerM** [comment]
`User.objects.filter(oauth2_provider_accesstoken__token="<your_access_token>")`
