### ISSUE TITLE
Old commit history

### ISSUE THREAD

**Issue by jayvdb** [wagnerdelima/drf-social-oauth2#6]
It is a bit unfortunate if this library looses the old contribution history.

Any chance you could re-create it with full history, in order to give credit to the [previous contributors](https://github.com/RealmTeam/django-rest-framework-social-oauth2/graphs/contributors)

**Comment by wagnerdelima** [comment]
Hey @jayvdb perhaps merging the .git/ from the old repo would conflict with this repo's. 

However I think we could add the contributors to the README file in order to give them credit. What do you think?
It's usually done like that in the open source world. Let me know and I can add them. i am sorry for our contributor's losses!

**Comment by jayvdb** [comment]
No, it is not *usually* done like that in the open source world.

Your .git is only hours old, and only has commits from a single person : you.

You can very easily backup your code, delete your .git, delete this GitHub repo even, and then re-add your code on top of the real history and then publish the updated .git.

**Comment by wagnerdelima** [comment]
> No, it is not _usually_ done like that in the open source world.
> 
> Your .git is only hours old, and only has commits from a single person : you.
> 
> You can very easily backup your code, delete your .git, delete this GitHub repo even, and then re-add your code on top of the real history and then publish the updated .git.

Done. Thank you for your inputs @jayvdb .
